---
abstract: 'A library for interacting with the myGengo API'
author:
  - 'Nathaniel Heinrichs'
build_requires:
  ExtUtils::MakeMaker: 6.62
  FindBin: 0
  Getopt::Long: 0
  Test::More: 0.88
  URI::Escape: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MyGengo
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  Digest::HMAC: 0
  Digest::SHA1: 0
  HTTP::Response: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Aliases: 0
  MooseX::NonMoose: 0
  MooseX::Types::DateTime: 0
  Scalar::Util: 0
  Throwable: 0
  URI: 0
  namespace::autoclean: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.010
